import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import "./globals.css";
import PassiveModal from "@/components/PassiveModal";
import { Button } from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: React.ReactNode;
  modal: React.ReactNode;
}

export default function RootLayout({ children, modal }: LayoutProps) {
  return (
    <html lang="en" className="dark text-foreground bg-background">
      <body>
        <Providers>
          <main id="appRoot">
            {children}
            {modal}
          </main>
        </Providers>
      </body>
    </html>
  );
}
