import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from './providers';
import './globals.css';
import TopNavBar from '@/components/TopNavBar';
import { getSession } from '@/service/user';
import localFont from 'next/font/local';
import './shim';

const inter = Inter({ subsets: ['latin'] });

const font = localFont({
  src: './SUIT-Variable.woff2',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type LayoutProps = {
  children: React.ReactNode;
  modal: React.ReactNode;
};

export default async function RootLayout({ children, modal }: LayoutProps) {
  const session = await getSession();

  return (
    <html lang="en" className={`bg-background text-foreground dark ${font.className}`}>
      <head>
        <link rel="icon" href="/icon?<generated>" type="image/<generated>" sizes="<generated>" />
        <link
          rel="apple-touch-icon"
          href="/apple-icon?<generated>"
          type="image/<generated>"
          sizes="<generated>"
        />
      </head>
      <body className="h-[100dvh] w-screen">
        <Providers className="flex h-full max-h-full w-full flex-col items-center">
          <TopNavBar className={''} isLoggedIn={session.isLoggedIn} />
          <main className="flex h-full w-full flex-col items-center px-2 lg:w-2/3 xl:w-1/2">
            {children}
            {modal}
          </main>
          {/* {session.isLoggedIn && <FloatingButton key="root" />} */}
        </Providers>
      </body>
    </html>
  );
}
